#!/usr/bin/env bash

# depends on procmail and mu packages
#
# for use with pipeout command in alot mail client

set -eou pipefail

message_path=$(</dev/stdin)

# create tmpdir and setup trap to delete it
tmpdir="$(mktemp -d)"
if [[ ! "$tmpdir" || ! -d "$tmpdir" ]]; then
  echo "Could not create temp dir"
  exit 1
fi
trap 'rm -rf -- "$tmpdir"' EXIT


mu extract --parts=1 $message_path --target-dir=$tmpdir
body=$(cat $tmpdir/part-1)

subject=$(cat $message_path \
    | formail -x Subject \
    `# remove beginning whitespace` \
    | sed -e 's/^\s*//' \
    `# replace newlines with spaces` \
    | sed -z 's/\n/ /g' \
    `# remove trailing whitespace` \
    | sed -e 's/\s*$//')


# remove $subject from $body if it exists
body=${body/$subject/}

# remove leading whitespace from body
body=$(echo "$body" | sed '/\S/,$!d')

echo "-----"
echo "$subject"
echo "$body"

